parameters:
  ite_filtration.form.type_extension.text.class: ITE\FiltrationBundle\Form\Extension\TextTypeFilterExtension
  ite_filtration.form.type_extension.form.class: ITE\FiltrationBundle\Form\Extension\FormTypeFilterExtension
  ite_filtration.form.type.range_filter.class: ITE\FiltrationBundle\Form\Type\RangeFilterType
  ite_filtration.form.type.filter_collection.class: ITE\FiltrationBundle\Form\Type\FilterCollectionType
  ite_filtration.form.type.callback_filter.class: ITE\FiltrationBundle\Form\Type\CallbackFilterType

services:
  ite_filtration.form.type_extension.text:
    class: %ite_filtration.form.type_extension.text.class%
    tags:
      - { name: form.type_extension, alias: text }

  ite_filtration.form.type_extension.form:
    class: %ite_filtration.form.type_extension.form.class%
    tags:
      - { name: form.type_extension, alias: form }

  ite_filtration.form.type.range_filter:
    class: %ite_filtration.form.type.range_filter.class%
    tags:
      - { name: form.type, alias: range_filter }

  ite_filtration.form.type.filter_collection:
    class: %ite_filtration.form.type.filter_collection.class%
    tags:
      - { name: form.type, alias: filter_collection }

  ite_filtration.form.type.callback_filter:
    class: %ite_filtration.form.type.callback_filter.class%
    tags:
      - { name: form.type, alias: callback_filter }