parameters:
  ite_filtration.manager.class: ITE\FiltrationBundle\Filtration\FiltrationManager
  ite_filtration.twig.extension.filtration.class: ITE\FiltrationBundle\Twig\Extension\FiltrationExtension
  ite_filtration.knp.pager_sortable.event_subscriber.class: ITE\FiltrationBundle\Pager\Event\Subscriber\Sortable\ArraySubscriber
  ite_filtration.knp.pager_sortable_disable_sorting.event_subscriber.class: ITE\FiltrationBundle\Pager\Event\Subscriber\Sortable\DisableSortingSubscriber

services:
  ite_filtration.manager:
    class: %ite_filtration.manager.class%
    arguments:
      - @form.factory
      - @request_stack
      - @event_dispatcher

  ite_filtrator: "@ite_filtration.manager"

  ite_filtration.twig.extension.filtration:
    class: %ite_filtration.twig.extension.filtration.class%
    arguments:
      - @ite_filtrator
    tags:
      - { name: twig.extension }

  ite_filtration.knp.pager_sortable_array.event_subscriber:
    class: %ite_filtration.knp.pager_sortable.event_subscriber.class%
    tags:
      - { name: kernel.event_subscriber }

  ite_filtration.knp.pager_sortable_disable_sorting.event_subscriber:
    class: %ite_filtration.knp.pager_sortable_disable_sorting.event_subscriber.class%
    tags:
      - { name: kernel.event_subscriber }

